name: GitHub Actions Vercel Commands
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - "feat/**"
  push:
    branches:
      - "feat/**"

jobs:
  Vercel-Commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel
      - name: add env var
        run: echo feat/HCD-1499_E | vercel env add TEST preview --token=${{ secrets.VERCEL_TOKEN }}
